apiVersion: v1
kind: Service
metadata:
  name: my-finhub-frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: frontend-port
    protocol: TCP
    port: 5001
    targetPort: 80
