apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
       - name: frontend
         image: cloud.canister.io:5000/miguelmcell/finhub-frontend
         ports:
         - containerPort: 80
         env:
          - name: "SERVERPORT"
            value: "80"
      imagePullSecrets:
      - name: regcred
