apiVersion: v1
kind: Service
metadata:
  name: my-finhub-backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 5002
    targetPort: 8443
