apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
       - name: backend
         image: cloud.canister.io:5000/miguelmcell/finhub-backend
         ports:
         - containerPort: 8443
         env:
          - name: "SERVERPORT"
            value: "8443"
      imagePullSecrets:
      - name: regcred
