apiVersion: v1
kind: Service
metadata:
  name: my-finhub-broker-service
spec:
  type: NodePort
  selector:
    app: broker-api
  ports:
  - name: broker-port
    protocol: TCP
    port: 5003
    targetPort: 5000
